### ISSUE TITLE
Register button

### ISSUE THREAD

**Issue by ryandougherty** [dhganey/mwa-capstone#9] opened 2014-11-15 23:15 UTC
Just a simple button to register with the database.

**Comment by dhganey** [comment] 2015-02-06 06:21
Are we supporting public registrations?

**Comment by ryandougherty** [comment] 2015-02-06 15:47
Maybe just an internal registration link? Just makes it easier for the DB maintainers to not have to manually add people (unless that is easy)

**Comment by dhganey** [comment] 2015-02-23 16:15
Duplicate of #29

**Closed by dhganey** 2015-02-23 16:15 UTC
Labels: feature
